sonar.projectKey=java-pti
sonar.projectName=Java PTI - open source
sonar.language=java

sonar.sources=./java-pti/silabs-pti/src/main
sonar.tests=./java-pti/silabs-pti/src/test
sonar.java.binaries=./java-pti/silabs-pti/build/libs/*.jar
